# install gnome-tweak-tool, arc-theme, dconf-cli, dconf-tools, gnome-shell-extensions, gnome-shell-extension-dash-to-panel
# use palenight theme from https://github.com/mdzhang/Gogh

# set system mono font to Nerd font
# and terminal font to system font

# to avoid keyboard not detected after suspend, update /etc/default/grub w/
#   GRUB_CMDLINE_LINUX_DEFAULT="quiet splash atkbd.reset"
# & sudo update-grub

# for proper suspend, update /etc/systemd/logind.conf w/
#   HandleSuspendKey=suspend
#   HandleLidSwitch=suspend
#   HandleLidSwitchDocked=suspend

# update BIOS for Linux optimized suspend
#   see https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Carbon_(Gen_6)#Automatic_(Linux_Vendor_Firmware_Service)

# sudo apt-get install network-manager-openvpn-gnome seahorse-nautilus
